name: Deploy Static Site

on:
  push:
    branches:
      - main  # 触发构建的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3
      
    - name: Checkout public repo
      uses: actions/checkout@v3
      with:
        repository: rainforeast/CADTR  # 替换为你的公共仓库名称
        token: ${{ secrets.WEB_TRY }}  # 使用个人访问令牌进行认证
        path: ./public-repo
        clean: true  # 确保检出时清理旧文件
        fetch-depth: 0  # 获取所有历史记录，确保完整克隆
        sparse-checkout-cone-mode: true
        fetch-tags: false
        lfs: false
        submodules: false
        set-safe-directory: true

    - name: Ensure no .git folder in public repo
      run: |
        if [ -d "./public-repo/.git" ]; then
          rm -rf ./public-repo/.git
        fi

    - name: Copy static files to public repo
      run: |
        rsync -av --exclude='./public-repo/' --exclude='.git' ./ ./public-repo/

    - name: Commit and push only static files
      run: |
        cd ./public-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Deploy from private repo" || echo "No changes to commit"
        git remote set-url origin https://${{ secrets.WEB_TRY }}@github.com/rainforeast/CADTR.git
        git push origin main  # 推送到公共仓库的main分支