name: Deploy Static Site

on:
  push:
    branches:
      - main  # 触发构建的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3
      
    - name: Checkout public repo
      uses: actions/checkout@v3
      with:
        repository: rainforeast/CADTR  # 替换为你的公共仓库名称
        token: ${{ secrets.WEB_TRY }}  # 使用个人访问令牌进行认证
        path: ./public-repo

    - name: Copy static files to public repo
      run: |
        cp -R * ./public-repo/

    - name: Commit and push only static files
      run: |
        cd ./public-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Deploy from private repo" || echo "No changes to commit"
        git push origin main  # 推送到公共仓库的gh-pages分支