name: Deploy Static Site to Public Repo

on:
  push:
    branches:
      - main  # 触发构建的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3
      with:
        repository: rainforeast/rainforeast.github.io  # 私有仓库名称
        token: ${{ secrets.WEB_TRY }}  # 使用个人访问令牌进行认证
        path: ./private-repo
        clean: true  # 确保检出时清理旧文件
        fetch-depth: 0  # 获取所有历史记录，确保完整克隆
        sparse-checkout-cone-mode: true
        fetch-tags: false
        lfs: false
        submodules: false
        set-safe-directory: true

    - name: Checkout public repo
      uses: actions/checkout@v3
      with:
        repository: rainforeast/CADTR  # 公共仓库名称
        token: ${{ secrets.WEB_TRY }}  # 使用个人访问令牌进行认证
        path: ./public-repo
        clean: true  # 确保检出时清理旧文件
        fetch-depth: 0  # 获取所有历史记录，确保完整克隆
        sparse-checkout-cone-mode: true
        fetch-tags: false
        lfs: false
        submodules: false
        set-safe-directory: true

    - name: Remove any nested directories from private repo
      run: |
        find ./private-repo -type d -name 'public-repo' -exec rm -rf {} +

    - name: Copy static files to public repo
      run: |
        rsync -av --exclude='.git' --exclude='.github' --delete ./private-repo/ ./public-repo/

    - name: Initialize git in public repo and commit changes
      run: |
        cd ./public-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Deploy from private repo" || echo "No changes to commit"

    - name: Set up git remote with token and push changes
      run: |
        cd ./public-repo
        git remote set-url origin https://x-access-token:${{ secrets.WEB_TRY }}@github.com/rainforeast/CADTR.git
        git push -u origin main  # 推送到公共仓库的main分支，请根据实际情况调整