name: Deploy to GitHub Pages from Main Branch

on:
  push:
    branches:
      - main  # 触发条件：当 main 分支有推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3
      with:
        repository: rainforeast/rainforeast.github.io  # 私有仓库名称
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}  # 使用个人访问令牌进行认证
        path: ./private-repo
        fetch-depth: 0  # 获取所有历史记录，确保完整克隆

    - name: Checkout public repo (for main branch)
      uses: actions/checkout@v3
      with:
        repository: rainforeast/CADTR  # 公共仓库名称
        path: ./public-repo
        ref: main  # 指定检出 main 分支

    - name: Build static site
      run: |
        mkdir -p ./public-repo/
        cp -r ./private-repo/CADTR/* ./public-repo/

    - name: Debug copied files in public repo
      run: |
        ls -la ./public-repo/

    - name: Commit and push to main branch
      run: |
        cd ./public-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Deploy CADTR folder from private repo" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push origin main  # 推送到公共仓库的 main 分支