name: Deploy CADTR Folder to Public Repo

on:
  push:
    paths:
      - 'CADTR/**'  # 只触发当 CADTR 文件夹中的文件发生变化时
    branches:
      - main  # 触发构建的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3
      with:
        repository: rainforeast/rainforeast.github.io  # 私有仓库名称
        token: ${{ secrets.WEB_TRY }}  # 使用个人访问令牌进行认证
        path: ./private-repo
        clean: true  # 确保检出时清理旧文件
        fetch-depth: 0  # 获取所有历史记录，确保完整克隆
        sparse-checkout-cone-mode: true
        fetch-tags: false
        lfs: false
        submodules: false
        set-safe-directory: true

    - name: Debug private repo directory content
      run: |
        ls -la ./private-repo/CADTR/

    - name: Checkout public repo (CADTR)
      uses: actions/checkout@v3
      with:
        repository: rainforeast/CADTR  # 公共仓库名称
        token: ${{ secrets.WEB_TRY }}  # 使用个人访问令牌进行认证
        path: ./public-repo-cadtr
        ref: main  # 指定检出 main 分支
        clean: true  # 确保检出时清理旧文件
        fetch-depth: 0  # 获取所有历史记录，确保完整克隆
        sparse-checkout-cone-mode: true
        fetch-tags: false
        lfs: false
        submodules: false
        set-safe-directory: true

    - name: Debug public repo directory content
      run: |
        ls -la ./public-repo-cadtr/

    - name: Remove any nested directories from private repo
      run: |
        find ./private-repo -type d -name 'public-repo-cadtr' -exec rm -rf {} +

    - name: Copy CADTR folder content to public repo
      run: |
        rsync -av --exclude='.git' --exclude='.github' --delete ./private-repo/CADTR/ ./public-repo-cadtr/

    - name: Debug copied files in public repo
      run: |
        ls -la ./public-repo-cadtr/

    - name: Initialize git in public repo and commit changes (CADTR)
      run: |
        cd ./public-repo-cadtr
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Deploy CADTR folder from private repo" || echo "No changes to commit"

    - name: Ensure only static files are in the public repo
      run: |
        cd ./public-repo-cadtr
        echo "/*" > .gitignore  # 忽略所有文件
        git add -f .gitignore  # 强制添加 .gitignore 文件
        git commit -m "Ensure only static files are in the public repo" || echo "No changes to commit"

    - name: Debug git status
      run: |
        cd ./public-repo-cadtr
        git status

    - name: Set up git remote with token and push changes (CADTR)
      run: |
        cd ./public-repo-cadtr
        git remote set-url origin https://x-access-token:${{ secrets.WEB_TRY }}@github.com/CADTR.git
        git push -u origin main  # 推送到公共仓库的main分支，请根据实际情况调整

    - name: Debug remote URL
      run: |
        cd ./public-repo-cadtr
        git remote -v